In [4]:
import pandas as pd
pd.set_option("mode.copy_on_write", True)
#This will not create copy of dataframe for .head() operation instead it will just return a view

In [2]:
class DataFrameReader:
    def __init__(self, file_path):
        self.file_path = file_path
        self.reader = None
        
    def set_reader(self, reader):
        self.reader = reader
    
    def read(self):
        if not self.reader:
            raise ValueError("No reader has been set.")
        return self.reader(self.file_path)
    
# Define reader functions
def csv_reader(file_path):
    return pd.read_csv(file_path,engine='pyarrow', dtype_backend='pyarrow')

def excel_reader(file_path):
    return pd.read_excel(file_path,engine='pyarrow', dtype_backend='pyarrow')

# Example usage
file_path = "../Data/usa_county_wise.csv"

# Create a DataFrameReader object and set the reader function
reader = DataFrameReader(file_path)
reader.set_reader(csv_reader)

# Read the DataFrame using the set reader function
df = reader.read()

df.head(5)

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Date,Confirmed,Deaths
0,16,AS,ASM,16,60.0,,American Samoa,US,-14.271000,-170.132000,"American Samoa, US",1/22/20,0,0
1,316,GU,GUM,316,66.0,,Guam,US,13.444300,144.793700,"Guam, US",1/22/20,0,0
2,580,MP,MNP,580,69.0,,Northern Mariana Islands,US,15.097900,145.673900,"Northern Mariana Islands, US",1/22/20,0,0
3,63072001,PR,PRI,630,72001.0,Adjuntas,Puerto Rico,US,18.180117,-66.754367,"Adjuntas, Puerto Rico, US",1/22/20,0,0
4,63072003,PR,PRI,630,72003.0,Aguada,Puerto Rico,US,18.360255,-67.175131,"Aguada, Puerto Rico, US",1/22/20,0,0